<?php
/**
 *Active_Life default Customer account link authorization template.
 * @author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 * @copyright 2020 worzewolf.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<div class="active-life_header-links">
    <div class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
        <a <?= /* @noEscape */
        $block->getLinkAttributes() ?><?= /* @noEscape */
        $dataPostParam ?>>
            <?= $block->escapeHtml($block->getLabel()) ?>
        </a>
    </div>
    <div class="active-life_about-block">
        <a href="http://activelifem2.local/"><?= $block->escapeHtmlAttr(__('Discover more about ActiveLife')) ?></a>
    </div>
</div>
<script>
    (function  () {
        require(["jquery","owlCarousel"],function($) {
            $(document).ready(function() {
                $(".active-life_header-links").owlCarousel({
                    items: 2,
                    loop: true,
                    navigation: false,
                    dots: false,
                    touchDrag: true,
                    mouseDrag: false,
                    responsive:{
                        320:{
                            items:1,
                            autoplay: true,
                            autoplayTimeout: 5000
                        },
                        968:{
                            items:2
                        }
                    }
                });
            });
        });
    })();
</script>
